Fixes #5 - Fallback
oyshan/fplstats pull request #6
Opened 2021-06-13 08:28 UTC by vongohren

Tror det skal være grei fallback, brukte ikke noe mer tid på å anlaysere hva potensielt utfall ville bli. Men kanskje du har en tanke på det?

2021-06-13 08:47 UTC, oyshan requested changes
Forslaget ditt funker, men tror det kan løses ved å bruke all picks istedet for starting picks:)

2021-06-13 08:47 UTC, oyshan commented on fplstats/analyzers.py
> +            vc_pick = next((x for x in gw1_starting_picks if x.is_vice_captain), None)
Tror dette kan løses ved å bytte gw1_starting_picks med gw1_all_picks. Da tror jeg ikke man trenger en fallback
```suggestion
            vc_pick = next((x for x in gw1_all_picks if x.is_vice_captain))
```

2021-06-13 08:47 UTC, oyshan commented on fplstats/analyzers.py
Da tror jeg ikke vi trenger denne fallback-logikken heller

2021-06-13 19:19 UTC, vongohren commented on fplstats/analyzers.py
> +            vc_pick = next((x for x in gw1_starting_picks if x.is_vice_captain), None)
Bekrefter at det funker så har oppdatert!

2021-06-13 19:19 UTC, vongohren commented on fplstats/analyzers.py
Stemmer

2021-06-14 09:01 UTC, oyshan approved these changes

2021-06-14 20:45 UTC, vongohren commented
@oyshan du må fortsatt merge :D

2021-06-14 21:11 UTC, merged